[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
test = 'test'
cache_path  = 'forge-cache'

solc_version = "0.8.24"
evm_version = "cancun"

optimizer = true
optimizer_runs = 777

[fuzz]
runs = 256
max_test_rejects = 10240000